appName: nginx-custom-index

namespace: custom-nginx

replicas: 1

configmap:
  name: nginx-custom-index-cm
  customHeader: "Welcome to Azure AKS!"


container:
  name: nginx
  image: nginx:latest
  resources:
    limits:
      memory: "20Mi"
      cpu: "0.001"
