apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Shlomi-Lantser/custom-nginx-proj.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAAyNLPyv6pdy1IBMu7jqIY+xLkzqP3veAv0uiHnTYDaQAAAJjVT24+1U9u
    PgAAAAtzc2gtZWQyNTUxOQAAACAAyNLPyv6pdy1IBMu7jqIY+xLkzqP3veAv0uiHnTYDaQ
    AAAEAWUm2Jpe0HDiIHMUxHWXAXmzuxcoaYt93e5qxLkuFQegDI0s/K/ql3LUgEy7uOohj7
    EuTOo/e94C/S6IedNgNpAAAAE3NsYW50c2Vyc0BnbWFpbC5jb20BAg==
    -----END OPENSSH PRIVATE KEY-----