apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example-rules
    role: alert-rules
  name: prom
spec:
  groups:
  - name: my-pod-demo-rules
    rules:     
    - alert: ContainerHighCpuUtilization
      expr: 100 * (sum(rate(container_cpu_usage_seconds_total{pod=~"nginx-custom-index-.+"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{pod=~"nginx-custom-index-.+", resource="cpu"}) by (pod)) > 80
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "High CPU utilization detected in pod {{ $labels.pod }}"
        title: 🚨 High CPU Utilization Alert 🚨
        description: |
          The container {{ $labels.pod }} is experiencing high CPU usage, exceeding 80%.
