prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelector:
       matchExpressions:
        - key: prometheus
          operator: In
          values:
          - example-rules


alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['severity']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'email-notifications'
      routes:
      - match:
        receiver: 'email-notifications'
        continue: true
    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: shlomi.lant@gmail.com
        from: shlomi.lant@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: shlomi.lant@gmail.com
        auth_identity: shlomi.lant@gmail.com
        auth_password: gqejavnartmtrjje
        send_resolved: true